dataSources:
  ds_master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://10.182.8.226:3316/db
    username: root
    password: root
  ds_slave1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://10.182.8.226:3326/db
    username: root
    password: root
  ds_slave2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://10.182.8.227:3336/db
    username: root
    password: root

rules:
  - !READWRITE_SPLITTING
    dataSources:
      ds_master, ds_slave1, ds_slave2
      primaryDataSourceName: ds_master
      replicaDataSourceNames:
        - ds_slave1,ds_slave2
      loadBalancerName: ROUND_ROBIN

props:
  sql-show: true

#dataSources:
#  write_ds:
#    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    jdbcUrl: jdbc:mysql://10.182.8.226:3316/db?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#  read_ds_0:
#    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    jdbcUrl: jdbc:mysql://10.182.8.226:3326/db?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#  read_ds_1:
#    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    jdbcUrl: jdbc:mysql://10.182.8.227:3336/db?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#
#rules:
#  - !READWRITE_SPLITTING
#    dataSources:
#      write_ds,read_ds_0,read_ds_1
#      pr_ds:
#        writeDataSourceName: write_ds
#        readDataSourceNames: [read_ds_0, read_ds_1]
